### PR TITLE
Fixes publish bug

### PR DESCRIPTION
**Pull request by purplecones**
This should fix the publish issue. Can you publish and check?

### CODE REVIEW

**Comment by jkrup** [comment]
I pushed this to `@beta`

**Comment by jkrup** [comment]
CircleCI is failing 😮

**Comment by purplecones** [comment]
hmm

**Comment by purplecones** [comment]
CircleCI keeps timing out.

```
pm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
```

**Pull request merged**
