### PR TITLE
Rewrite (WIP)

### PR DESCRIPTION
**Pull request by purplecones**
This should resolve many of the outstanding issues. Still work in progress. Also requires tests.

### CODE REVIEW

**Comment by purplecones** [comment]
@jkrup can you test this version on your side? Deploy a few apps with it. The UX at this point should be identical to the first version but the internals are completely new.

A few things that are still needed:
- A lot more tests. I tried making all the individual functions as test-friendly as possible but I'm sure we can rewrite some to be more testable.
- I feel that error handling can be improved. For some reason I wasn't able to throw errors back up to `main` so most of the error handling is down deeper in the stack.
- I'm thinking we should also probably check if the `cwd` is a meteor app.

Let me know what you think

**Comment by purplecones** [comment]
Also needs some logic to handle `now.json` that users can have in the meteor app. Need to copy it to the build folder before deploy.

**Comment by purplecones** [comment]
We should also consider implementing a different docker approach such as mentioned here https://github.com/jkrup/meteor-now/issues/52. Small deployments are okay but most apps are much bigger. One of my apps which is relatively small but it split into 352 files to upload.

**Comment by purplecones** [comment]
@jkrup How do you feel about publishing this as meteor-now@next for now ?

**Comment by jkrup** [comment]
Actually I think we can just make this live.

**Comment by purplecones** [comment]
There's an issue when installing through npm. Can you roll back so we can test with `beta` tag or something similar?

```
🏕  meteor-now -d
/usr/local/lib/node_modules/meteor-now/build/main.js:358
var getVersion = async function getVersion() {
                       ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

**Pull request merged**
