### PR TITLE
Use node 8.x

### PR DESCRIPTION
**Pull request by timneutkens**
Fixes https://github.com/jkrup/meteor-now/issues/90, meteor/meteor/issues/9470 and some user reports on zeit.chat

### CODE REVIEW

**Comment by jkrup** [comment]
Ah Thanks @timneutkens ! Looks good, but I'll test it tonight.

**Comment by timneutkens** [comment]
Thanks, let me know when it's released so I can let some people know on slack 👍 👍

**Comment by jkrup** [comment]
Hey @timneutkens just published v0.5.3 to NPM.

**Comment by timneutkens** [comment]
Great @jkrup!

**Pull request merged**
